# install-services.yml
# Install need packages on servers

---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Installing apache
        yum: name=httpd state=present
      - name: Ensure apache starts
        service: name=httpd state=started enabled=yes
       

  - hosts: webservers
    become: true
    tasks:
      - name: Installing install
        yum:
          name: 
            - httpd
            - php
          state: present
      - name: Ensure apache starts
        service: name=httpd start=started enabled=yes